% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\documentclass[
]{article}
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{amsmath,amssymb}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\newsavebox\pandoc@box
\newcommand*\pandocbounded[1]{% scales image to fit in text height/width
  \sbox\pandoc@box{#1}%
  \Gscale@div\@tempa{\textheight}{\dimexpr\ht\pandoc@box+\dp\pandoc@box\relax}%
  \Gscale@div\@tempb{\linewidth}{\wd\pandoc@box}%
  \ifdim\@tempb\p@<\@tempa\p@\let\@tempa\@tempb\fi% select the smaller of both
  \ifdim\@tempa\p@<\p@\scalebox{\@tempa}{\usebox\pandoc@box}%
  \else\usebox{\pandoc@box}%
  \fi%
}
% Set default figure placement to htbp
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={BIOLM0039 - Investigating Giraffe Body Mass},
  pdfauthor={Archie Benn (1935263)},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{BIOLM0039 - Investigating Giraffe Body Mass}
\author{Archie Benn (1935263)}
\date{2026-05-03}

\begin{document}
\maketitle

Word count: 4997 (using
\texttt{pandoc\ BIOLM0039\_exam.Rmd\ -\/-to=plain\ \textbar{}\ wc\ -w})

\subsection{1. Set workspace}\label{set-workspace}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# reset environment}
\FunctionTok{rm}\NormalTok{(}\AttributeTok{list=}\FunctionTok{ls}\NormalTok{())}

\CommentTok{\# load libraries}
\FunctionTok{library}\NormalTok{(tidyverse)}
\FunctionTok{library}\NormalTok{(wesanderson)}
\FunctionTok{library}\NormalTok{(performance)}
\FunctionTok{library}\NormalTok{(Hmisc)}
\FunctionTok{library}\NormalTok{(ggpubr)}
\FunctionTok{library}\NormalTok{(rstatix)}
\FunctionTok{library}\NormalTok{(fitdistrplus)}
\FunctionTok{library}\NormalTok{(MASS)}
\FunctionTok{library}\NormalTok{(see)}
\FunctionTok{library}\NormalTok{(TMB)}
\FunctionTok{library}\NormalTok{(glmmTMB)}
\FunctionTok{library}\NormalTok{(DHARMa)}
\FunctionTok{library}\NormalTok{(data.table)}
\FunctionTok{library}\NormalTok{(caret)}
\FunctionTok{library}\NormalTok{(modelbased)}
\FunctionTok{library}\NormalTok{(broom.mixed)}
\FunctionTok{library}\NormalTok{(dotwhisker)}
\FunctionTok{library}\NormalTok{(ggeffects)}
\end{Highlighting}
\end{Shaded}

\subsection{2. Import and check Data}\label{import-and-check-data}

Load in the data (tsv file saved from GitHub) as a tibble:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{df }\OtherTok{\textless{}{-}} \FunctionTok{read\_tsv}\NormalTok{(}\StringTok{"../data/mass\_sj19031.tsv"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

Describe to get an overview of the data:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{describe}\NormalTok{(df)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## df 
## 
##  10  Variables      870  Observations
## --------------------------------------------------------------------------------
## student_id 
##        n  missing distinct    value 
##      870        0        1  sj19031 
##                   
## Value      sj19031
## Frequency      870
## Proportion       1
## --------------------------------------------------------------------------------
## species 
##        n  missing distinct    value 
##      870        0        1  Giraffe 
##                   
## Value      Giraffe
## Frequency      870
## Proportion       1
## --------------------------------------------------------------------------------
## park 
##        n  missing distinct 
##      870        0        4 
##                                                           
## Value           Golden Tusk Safari    Lionshade Wilderness
## Frequency                      264                     186
## Proportion                   0.303                   0.214
##                                                           
## Value      Savanna Whisper Reserve      Zebra Horizon Park
## Frequency                      189                     231
## Proportion                   0.217                   0.266
## --------------------------------------------------------------------------------
## observer 
##        n  missing distinct 
##      870        0        5 
##                                         
## Value      Obs_1 Obs_2 Obs_3 Obs_4 Obs_5
## Frequency    147   204   159   183   177
## Proportion 0.169 0.234 0.183 0.210 0.203
## --------------------------------------------------------------------------------
## body_mass 
##        n  missing distinct     Info     Mean  pMedian      Gmd      .05 
##      870        0      290        1     1271     1233    383.9    844.2 
##      .10      .25      .50      .75      .90      .95 
##    889.9   1009.1   1212.1   1456.5   1673.3   1799.4 
## 
## lowest : 587.917 665.151 681.379 690.192 690.787
## highest: 2404.45 2775.11 3319.15 3503.69 4682.4 
## --------------------------------------------------------------------------------
## landscape 
##        n  missing distinct 
##      861        9        2 
##                       
## Value       Flat Hilly
## Frequency    441   420
## Proportion 0.512 0.488
## --------------------------------------------------------------------------------
## vegetation 
##        n  missing distinct 
##      861        9        2 
##                       
## Value      Dense  Open
## Frequency    426   435
## Proportion 0.495 0.505
## --------------------------------------------------------------------------------
## lion_presence 
##        n  missing distinct 
##      861        9        5 
##                                                   
## Value       Absent  Asbent Preesnt Preseet Present
## Frequency      405       3       3       3     447
## Proportion   0.470   0.003   0.003   0.003   0.519
## --------------------------------------------------------------------------------
## env_var 
##        n  missing distinct 
##      870        0        3 
##                                                                 
## Value      average_annual_rainfall_mm       distance_to_water_km
## Frequency                         290                        290
## Proportion                      0.333                      0.333
##                                      
## Value      predator_density_per_sq_km
## Frequency                         290
## Proportion                      0.333
## --------------------------------------------------------------------------------
## env_value 
##         n   missing  distinct      Info      Mean   pMedian       Gmd       .05 
##       862         8       862         1     334.9     317.5     481.3    0.4668 
##       .10       .25       .50       .75       .90       .95 
##    0.6515    1.2368    3.5664  795.3547 1161.8979 1290.3489 
## 
## lowest : 0.101891 0.167874 0.172813 0.228129 0.259863
## highest: 1712.42  1714.88  1729.07  1737.42  1807.51 
## --------------------------------------------------------------------------------
\end{verbatim}

\texttt{df} contains the following:\\
- Giraffe mass (kg) collected from 5 observers across 4 parks\\
- Two level categorical data for \texttt{lion\_presence},
\texttt{vegetation}, and \texttt{landscape}\\
- Continuous data on average annual rainfall, distance to water, and
predator density\\
- Missing values in \texttt{landscape}, \texttt{vegetation},
\texttt{lion\_presence}, \texttt{env\_value}\\
- 5 distinct values for \texttt{lion\_presence} -\textgreater{} Typos in
`Absent' or `Present'

\subsection{2. Tidying data}\label{tidying-data}

\subsubsection{2.1 Outliers}\label{outliers}

Boxplot to check outliers and see a general distribution of body mass
over the full dataset \texttt{df}:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# boxplot of entire dataset mass to check potential outliers}
\NormalTok{mass\_box }\OtherTok{\textless{}{-}}\NormalTok{ df }\SpecialCharTok{\%\textgreater{}\%}
  
  \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =} \StringTok{""}\NormalTok{, }\AttributeTok{y =}\NormalTok{ body\_mass)) }\SpecialCharTok{+}
  
  \CommentTok{\# reduce width to 0.25}
  \FunctionTok{geom\_boxplot}\NormalTok{(}\AttributeTok{width =} \FloatTok{0.25}\NormalTok{, }\AttributeTok{fill =} \FunctionTok{wes\_palette}\NormalTok{(}\StringTok{"IsleofDogs1"}\NormalTok{)[}\DecValTok{1}\NormalTok{]) }\SpecialCharTok{+}
  
  \CommentTok{\# aesthetics}
  \FunctionTok{theme\_lucid}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Box plot of giraffe mass across original dataset"}\NormalTok{) }\SpecialCharTok{+}
  
  \CommentTok{\# centre title}
  \FunctionTok{theme}\NormalTok{(}\AttributeTok{plot.title =} \FunctionTok{element\_text}\NormalTok{(}\AttributeTok{hjust =} \FloatTok{0.5}\NormalTok{)) }\SpecialCharTok{+}
  \FunctionTok{xlab}\NormalTok{(}\StringTok{""}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{ylab}\NormalTok{(}\StringTok{"Body mass (kg)"}\NormalTok{)}

\NormalTok{mass\_box}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{BIOLM0039_exam_files/figure-latex/unnamed-chunk-4-1.pdf}}

Box plot identifies 5 potential mass outliers in \texttt{df} using the
IQR criterion.

An outlier data frame will be created using which will be used to remove
these data during cleaning. This is justified biologically as giraffes
rarely exceed 2000kg and outliers are identified statistically:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# create outlier data frame}
\NormalTok{outlier\_df }\OtherTok{\textless{}{-}} \FunctionTok{identify\_outliers}\NormalTok{(}\AttributeTok{data =}\NormalTok{ df,}
                  \AttributeTok{variable =} \StringTok{"body\_mass"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

The dataset \texttt{df} is also in long format, and to have each row as
an individual observation will be transformed to wide format during
cleaning.

\subsubsection{2.2 Create cleaned data
frame}\label{create-cleaned-data-frame}

A clean data frame will be created based on the information above:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# using tidyverse}
\NormalTok{df\_clean }\OtherTok{\textless{}{-}}\NormalTok{ df }\SpecialCharTok{\%\textgreater{}\%}
  
  \CommentTok{\# remove outliers using the outlier data frame:}
  \FunctionTok{anti\_join}\NormalTok{(outlier\_df)  }\SpecialCharTok{\%\textgreater{}\%}
  
  \CommentTok{\# long to wide format df:}
  \FunctionTok{pivot\_wider}\NormalTok{(}\AttributeTok{names\_from =}\NormalTok{ env\_var, }\AttributeTok{values\_from =}\NormalTok{ env\_value) }\SpecialCharTok{\%\textgreater{}\%}

  \CommentTok{\# remove NA values including those in the new \textquotesingle{}wide columns\textquotesingle{}:}
  \FunctionTok{drop\_na}\NormalTok{(landscape, vegetation, lion\_presence, distance\_to\_water\_km, average\_annual\_rainfall\_mm, predator\_density\_per\_sq\_km) }


\CommentTok{\# fix typos in lion\_presence (no need to remove as very clearly \textquotesingle{}Present\textquotesingle{} or \textquotesingle{}Absent\textquotesingle{} typos)}
\NormalTok{df\_clean}\SpecialCharTok{$}\NormalTok{lion\_presence[df\_clean}\SpecialCharTok{$}\NormalTok{lion\_presence }\SpecialCharTok{==} \StringTok{"Preesnt"}\NormalTok{] }\OtherTok{\textless{}{-}} \StringTok{"Present"} 
\NormalTok{df\_clean}\SpecialCharTok{$}\NormalTok{lion\_presence[df\_clean}\SpecialCharTok{$}\NormalTok{lion\_presence }\SpecialCharTok{==} \StringTok{"Preseet"}\NormalTok{] }\OtherTok{\textless{}{-}} \StringTok{"Present"}
\NormalTok{df\_clean}\SpecialCharTok{$}\NormalTok{lion\_presence[df\_clean}\SpecialCharTok{$}\NormalTok{lion\_presence }\SpecialCharTok{==} \StringTok{"Asbent"}\NormalTok{] }\OtherTok{\textless{}{-}} \StringTok{"Absent"}
\end{Highlighting}
\end{Shaded}

\texttt{df\_clean} now has no missing variables, fixed
\texttt{lion\_presence} typos, no statistical outiers based on the
original \texttt{df}, and each row is an individual observation.

\subsection{3. Variables and hypotheses}\label{variables-and-hypotheses}

\subsubsection{3.1 Variables}\label{variables}

\texttt{df\_clean} contains variables as follows:

\textbf{Response:}\\
- \texttt{body\_mass}

\textbf{Predictors (fixed):}\\
- Categorical = \texttt{landscape}, \texttt{vegetation},
\texttt{lion\_presence}\\
- Continuous = \texttt{distance\_to\_water\_km},
\texttt{average\_annual\_rainfall\_mm}, and
\texttt{predator\_density\_per\_sq\_km}

\textbf{Predictors (random):}\\
These two groups only have 4 and 5 levels each which could make variance
estimates unstable but will be included as random effects to account for
clustering among observations. - Groups/grouping: \texttt{park},
\texttt{observer}

These data are spatially structured, and no information on temporal
structure is provided. Need to consider if random effects will be
considered as slopes or intercepts, and any interactions when forming
models.

The response (body mass) is continuous and \(\geq\) 0, which allows for
Gaussian and/or Gamma if a GLMM is to be used.

\paragraph{3.1.1 Crossed or nested random
effects?}\label{crossed-or-nested-random-effects}

If any observer makes observations in \(\gt\) 1 park, the random effects
should be crossed, but if observers are contained within only one park
and do not make observations elsewhere, they can be treated as nested. A
contingency table can show the number of observations for each observer
across each park:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{table}\NormalTok{(df\_clean}\SpecialCharTok{$}\NormalTok{observer, df\_clean}\SpecialCharTok{$}\NormalTok{park)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##        
##         Golden Tusk Safari Lionshade Wilderness Savanna Whisper Reserve
##   Obs_1                 15                   10                      10
##   Obs_2                 22                   13                      15
##   Obs_3                  9                    8                      14
##   Obs_4                 17                   12                      10
##   Obs_5                 14                   15                      11
##        
##         Zebra Horizon Park
##   Obs_1                 11
##   Obs_2                 12
##   Obs_3                 20
##   Obs_4                 17
##   Obs_5                 14
\end{verbatim}

So each observer makes observations at all parks, therefore the random
effects will be crossed.

\subsubsection{3.2 Hypotheses}\label{hypotheses}

The following null and alternative hypotheses are proposed to test
giraffe body mass:

\[
H_0: \text{None of the factors included in this dataset have a significant effect on giraffe body mass}\\
H_1: \text{At least one factor included in this dataset has a significant effect on giraffe body mass}
\]

\subsection{4. Raw data exploration}\label{raw-data-exploration}

\subsubsection{4.1 Giraffe mass across each park and
observer:}\label{giraffe-mass-across-each-park-and-observer}

\paragraph{Park violin plot:}\label{park-violin-plot}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{plot\_mass\_parks }\OtherTok{\textless{}{-}}\NormalTok{ df\_clean }\SpecialCharTok{\%\textgreater{}\%}
  
  \FunctionTok{ggplot}\NormalTok{(}\AttributeTok{mapping =} \FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ park, }\AttributeTok{y =}\NormalTok{ body\_mass)) }\SpecialCharTok{+}
  
  \CommentTok{\# violin plot }
  \FunctionTok{geom\_violin}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{fill =}\NormalTok{ park)) }\SpecialCharTok{+} 
  
  \CommentTok{\# hide redundant legend}
  \FunctionTok{guides}\NormalTok{(}\AttributeTok{fill =} \StringTok{"none"}\NormalTok{) }\SpecialCharTok{+}
  
  \CommentTok{\# add boxplot }
  \FunctionTok{geom\_boxplot}\NormalTok{(}\AttributeTok{width =} \FloatTok{0.1}\NormalTok{, }\AttributeTok{col =} \StringTok{"black"}\NormalTok{)}\SpecialCharTok{+}
  
  
  
  \CommentTok{\# aesthetics}
  \FunctionTok{scale\_fill\_manual}\NormalTok{(}\AttributeTok{values =} \FunctionTok{wes\_palette}\NormalTok{(}\StringTok{"Darjeeling2"}\NormalTok{)) }\SpecialCharTok{+}
  \FunctionTok{ggtitle}\NormalTok{(}\StringTok{"Violin plot of giraffe mass across the parks"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{theme}\NormalTok{(}\AttributeTok{axis.text.x =} \FunctionTok{element\_text}\NormalTok{(}\AttributeTok{angle =} \DecValTok{45}\NormalTok{)) }\SpecialCharTok{+}
  \FunctionTok{ylab}\NormalTok{(}\StringTok{"Body mass (kg)"}\NormalTok{) }\SpecialCharTok{+} 
  \FunctionTok{xlab}\NormalTok{(}\StringTok{"Park"}\NormalTok{) }

\NormalTok{plot\_mass\_parks}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{BIOLM0039_exam_files/figure-latex/unnamed-chunk-8-1.pdf}}

Zebra Horizon Park appears to have a slightly raised mean giraffe mass
compared to the other three parks.

\paragraph{Observer violin plot}\label{observer-violin-plot}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{df\_clean }\SpecialCharTok{\%\textgreater{}\%}
  
  \FunctionTok{ggplot}\NormalTok{(}\AttributeTok{mapping =} \FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ observer, }\AttributeTok{y =}\NormalTok{ body\_mass)) }\SpecialCharTok{+}
  
  \CommentTok{\# violin plot }
  \FunctionTok{geom\_violin}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{fill =}\NormalTok{ observer)) }\SpecialCharTok{+} 
  
  \CommentTok{\# hide redundant legend}
  \FunctionTok{guides}\NormalTok{(}\AttributeTok{fill =} \StringTok{"none"}\NormalTok{) }\SpecialCharTok{+}
  
  \CommentTok{\# add boxplot }
  \FunctionTok{geom\_boxplot}\NormalTok{(}\AttributeTok{width =} \FloatTok{0.1}\NormalTok{, }\AttributeTok{col =} \StringTok{"black"}\NormalTok{)}\SpecialCharTok{+}
  
  
  
  \CommentTok{\# aesthetics}
  \FunctionTok{scale\_fill\_manual}\NormalTok{(}\AttributeTok{values =} \FunctionTok{wes\_palette}\NormalTok{(}\StringTok{"AsteroidCity1"}\NormalTok{)) }\SpecialCharTok{+}
  \FunctionTok{ggtitle}\NormalTok{(}\StringTok{"Violin Plot of Giraffe Mass Recorded Across the Observers"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{ylab}\NormalTok{(}\StringTok{"Body mass (kg)"}\NormalTok{) }\SpecialCharTok{+} 
  \FunctionTok{xlab}\NormalTok{(}\StringTok{"Observer"}\NormalTok{) }
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{BIOLM0039_exam_files/figure-latex/unnamed-chunk-9-1.pdf}}

\subsubsection{4.2 Scatter plots}\label{scatter-plots}

Log distance to water:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# scatter plot}
\NormalTok{df\_clean }\SpecialCharTok{\%\textgreater{}\%}
  
  \CommentTok{\# log the distance to water (+1 for positive x axis)}
  \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x=}\FunctionTok{log}\NormalTok{(distance\_to\_water\_km }\SpecialCharTok{+} \DecValTok{1}\NormalTok{), }\AttributeTok{y=}\NormalTok{body\_mass)) }\SpecialCharTok{+}
  
  \CommentTok{\# plot data points}
  \FunctionTok{geom\_point}\NormalTok{(}\AttributeTok{col=}\FunctionTok{wes\_palette}\NormalTok{(}\StringTok{"AsteroidCity2"}\NormalTok{)[}\DecValTok{1}\NormalTok{]) }\SpecialCharTok{+}
  
  \CommentTok{\# add linear regression}
  \FunctionTok{geom\_smooth}\NormalTok{(}\AttributeTok{method =} \StringTok{"lm"}\NormalTok{, }\AttributeTok{se =} \ConstantTok{FALSE}\NormalTok{, }\AttributeTok{color =} \StringTok{"black"}\NormalTok{, }\AttributeTok{formula =}\NormalTok{ y}\SpecialCharTok{\textasciitilde{}}\NormalTok{x, }\AttributeTok{linetype =} \StringTok{"dashed"}\NormalTok{) }\SpecialCharTok{+}
  
  \CommentTok{\# aesthetics}
  \FunctionTok{ggtitle}\NormalTok{(}\StringTok{"Giraffe Mass Against Distance to Water Across Parks"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{xlab}\NormalTok{(}\StringTok{"log(Distance to water (km))"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{ylab}\NormalTok{(}\StringTok{"Body mass (kg)"}\NormalTok{) }\SpecialCharTok{+}
  
  \CommentTok{\# group by park}
  \FunctionTok{facet\_wrap}\NormalTok{(. }\SpecialCharTok{\textasciitilde{}}\NormalTok{ park) }\SpecialCharTok{+}
  \FunctionTok{theme\_lucid}\NormalTok{() }
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{BIOLM0039_exam_files/figure-latex/unnamed-chunk-10-1.pdf}}

The distance to water appears to have a slight positive effect on body
mass across 3 out of the 4 parks.

Similar plots were created for average annual rainfall and predator
density, both showing weak relationships to body mass.

\subsubsection{4.3 Distribution and transformation
checks}\label{distribution-and-transformation-checks}

Body mass is strictly positive and continuous, as such the main families
involved for a model are likely Gaussian and Gamma. A histogram of body
mass and Box-Cox will be used to assess potential transformations to
attempt later.

\paragraph{Histogram with overlaid reference normal
distribution:}\label{histogram-with-overlaid-reference-normal-distribution}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{df\_clean }\SpecialCharTok{\%\textgreater{}\%}
  
  \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ body\_mass)) }\SpecialCharTok{+}
  
  \CommentTok{\# add histogram with bin width at 50kg and scale using ..density..}
  \FunctionTok{geom\_histogram}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{y =}\NormalTok{ ..density..), }\AttributeTok{fill =} \FunctionTok{wes\_palette}\NormalTok{(}\StringTok{"Cavalcanti1"}\NormalTok{)[}\DecValTok{4}\NormalTok{], }\AttributeTok{color =} \StringTok{"black"}\NormalTok{, }\AttributeTok{binwidth =} \DecValTok{50}\NormalTok{) }\SpecialCharTok{+}
  
  \CommentTok{\# overlay normal distribution with same mean and sd as body mass}
  \FunctionTok{stat\_function}\NormalTok{(}\AttributeTok{fun =}\NormalTok{ dnorm,}
                \AttributeTok{args =} \FunctionTok{list}\NormalTok{(}
                  \AttributeTok{mean =} \FunctionTok{mean}\NormalTok{(df\_clean}\SpecialCharTok{$}\NormalTok{body\_mass),}
                  \AttributeTok{sd =} \FunctionTok{sd}\NormalTok{(df\_clean}\SpecialCharTok{$}\NormalTok{body\_mass)),}
                \AttributeTok{linetype =} \StringTok{"dashed"}\NormalTok{) }\SpecialCharTok{+}
  
  \CommentTok{\# aesthetics}
  \FunctionTok{theme\_minimal}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Histogram of giraffe body mass"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{xlab}\NormalTok{(}\StringTok{"Body mass (kg)"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{ylab}\NormalTok{(}\StringTok{"Density"}\NormalTok{) }
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{BIOLM0039_exam_files/figure-latex/unnamed-chunk-11-1.pdf}}

Histogram indicates a right skewed body mass in this cleaned data.
Transformations may aid approximating to normal.

\paragraph{Box-Cox}\label{box-cox}

Box-Cox from \texttt{MASS} can help to see whether a power
transformation will approximate the data to normal for Gaussian models.
Box-Cox provides a value, \(\lambda\), which has the greatest log
likelihood for approximating normal given the data.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# first create a linear model of the body mass, intercept only}
\NormalTok{lm\_body\_mass  }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(body\_mass }\SpecialCharTok{\textasciitilde{}} \DecValTok{1}\NormalTok{, df\_clean)}

\CommentTok{\# apply box{-}cos to generate a log{-}likelihood plot which tests lambda from {-}2 to 2, step 0.1}
\FunctionTok{boxcox}\NormalTok{(lm\_body\_mass, }\AttributeTok{lambda =} \FunctionTok{seq}\NormalTok{(}\SpecialCharTok{{-}}\DecValTok{2}\NormalTok{, }\DecValTok{2}\NormalTok{, }\FloatTok{0.1}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{BIOLM0039_exam_files/figure-latex/unnamed-chunk-12-1.pdf}}

From this, highest log-likelihood \(\lambda \approx\) 0.25 which is
between a log (\(\lambda = 0\)) and a cube root (\(\lambda = 1/3\))
transformation, and means non-transformed (\(\lambda = 1\)) is unlikely
to fit as well. This, along with the positive and right skewed response,
suggests the following transformations for \texttt{fitdistr} testing
below:

\begin{itemize}
\tightlist
\item
  Gamma family with raw data\\
\item
  Log and cube-root transformed responses with Gaussian family
\end{itemize}

\subsubsection{4.4 Family checks}\label{family-checks}

Using \texttt{fitdistr} to assess potential error structures:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# log response with gaussian }
\FunctionTok{plot}\NormalTok{(}\FunctionTok{fitdist}\NormalTok{(}\FunctionTok{log}\NormalTok{(df\_clean}\SpecialCharTok{$}\NormalTok{body\_mass), }\StringTok{"norm"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{BIOLM0039_exam_files/figure-latex/unnamed-chunk-13-1.pdf}}

Above plot demonstrates a suitable fit for log transformed response with
Gaussian, and was repeated for both Gamma and cube-root transformed
Gaussian, with each showing adequate fit. Will move on to fitting
candidate models.

\subsection{5. Model fitting}\label{model-fitting}

\subsubsection{Log transformed Gaussian
Model}\label{log-transformed-gaussian-model}

Log transformed response GLMM with the Gaussian family (identity link),
including all predictors. Random effects will be included as intercepts
(not slopes), as effects are assumed to be the same across levels within
groups and to avoid overfitting with the limited number of levels in
each (4 and 5).

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# fit random effects model}
\NormalTok{glmm\_gauss\_log }\OtherTok{\textless{}{-}} \FunctionTok{glmmTMB}\NormalTok{(}

  \CommentTok{\# log transformed response \textasciitilde{} all fixed effects:}
  \FunctionTok{log}\NormalTok{(body\_mass) }\SpecialCharTok{\textasciitilde{}}\NormalTok{ landscape }\SpecialCharTok{+}
\NormalTok{    vegetation }\SpecialCharTok{+}
\NormalTok{    lion\_presence }\SpecialCharTok{+}
\NormalTok{    distance\_to\_water\_km }\SpecialCharTok{+}
\NormalTok{    average\_annual\_rainfall\_mm }\SpecialCharTok{+}
\NormalTok{    predator\_density\_per\_sq\_km }\SpecialCharTok{+} 
    
    \CommentTok{\# crossed random effects (park and observer), each with its own intercept:}
\NormalTok{    (}\DecValTok{1} \SpecialCharTok{|}\NormalTok{ park) }\SpecialCharTok{+}
\NormalTok{    (}\DecValTok{1} \SpecialCharTok{|}\NormalTok{ observer),}
  
  \AttributeTok{data =}\NormalTok{ df\_clean,}
  
  \AttributeTok{family =} \FunctionTok{gaussian}\NormalTok{()}
\NormalTok{)}

\FunctionTok{summary}\NormalTok{(glmm\_gauss\_log)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  Family: gaussian  ( identity )
## Formula:          
## log(body_mass) ~ landscape + vegetation + lion_presence + distance_to_water_km +  
##     average_annual_rainfall_mm + predator_density_per_sq_km +  
##     (1 | park) + (1 | observer)
## Data: df_clean
## 
##       AIC       BIC    logLik -2*log(L)  df.resid 
##     -48.9     -12.9      34.4     -68.9       259 
## 
## Random effects:
## 
## Conditional model:
##  Groups   Name        Variance Std.Dev.
##  park     (Intercept) 0.004804 0.06931 
##  observer (Intercept) 0.005935 0.07704 
##  Residual             0.042434 0.20599 
## Number of obs: 269, groups:  park, 4; observer, 5
## 
## Dispersion estimate for gaussian family (sigma^2): 0.0424 
## 
## Conditional model:
##                              Estimate Std. Error z value Pr(>|z|)    
## (Intercept)                 7.138e+00  7.814e-02   91.34   <2e-16 ***
## landscapeHilly             -4.104e-02  2.542e-02   -1.61   0.1065    
## vegetationOpen             -3.825e-02  2.547e-02   -1.50   0.1332    
## lion_presencePresent        1.957e-02  2.599e-02    0.75   0.4515    
## distance_to_water_km        1.127e-02  5.123e-03    2.20   0.0279 *  
## average_annual_rainfall_mm -5.725e-05  4.409e-05   -1.30   0.1941    
## predator_density_per_sq_km -5.923e-04  1.074e-02   -0.06   0.9560    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
\end{verbatim}

\paragraph{\texorpdfstring{Model check 1: Residual structure with
\texttt{DHARMa}:}{Model check 1: Residual structure with DHARMa:}}\label{model-check-1-residual-structure-with-dharma}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# simulate residuals for model with 1000 simulations (reduce stochastic error and stabilises values):}
\FunctionTok{plot}\NormalTok{(}\FunctionTok{simulateResiduals}\NormalTok{(glmm\_gauss\_log, }\AttributeTok{n =}\DecValTok{1000}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{BIOLM0039_exam_files/figure-latex/unnamed-chunk-15-1.pdf}}

No dispersion or deviation warnings indicate this model provides a good
fit to the data.

\paragraph{Model check 2: Multicollinearity between
predictors:}\label{model-check-2-multicollinearity-between-predictors}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{check\_collinearity}\NormalTok{(glmm\_gauss\_log)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # Check for Multicollinearity
## 
## Low Correlation
## 
##                        Term  VIF      VIF 95% CI adj. VIF Tolerance
##                   landscape 1.01 [1.00, 1481.03]     1.00      0.99
##                  vegetation 1.01 [1.00,  187.59]     1.01      0.99
##               lion_presence 1.05 [1.00,    1.70]     1.02      0.96
##        distance_to_water_km 1.02 [1.00,    8.65]     1.01      0.98
##  average_annual_rainfall_mm 1.05 [1.00,    1.65]     1.02      0.95
##  predator_density_per_sq_km 1.04 [1.00,    1.86]     1.02      0.96
##  Tolerance 95% CI
##      [0.00, 1.00]
##      [0.01, 1.00]
##      [0.59, 1.00]
##      [0.12, 1.00]
##      [0.61, 1.00]
##      [0.54, 1.00]
\end{verbatim}

VIF values \textasciitilde1 indicate low multicollinearity between
predictors in this model, with well estimated coefficients and \(p\)
values.

\paragraph{\texorpdfstring{Model check 3: Overdispersion checks with
\texttt{DHARMa}}{Model check 3: Overdispersion checks with DHARMa}}\label{model-check-3-overdispersion-checks-with-dharma}

For a more thorough overdispersion check:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{testDispersion}\NormalTok{(glmm\_gauss\_log)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{BIOLM0039_exam_files/figure-latex/unnamed-chunk-17-1.pdf}}

\begin{verbatim}
## 
##  DHARMa nonparametric dispersion test via sd of residuals fitted vs.
##  simulated
## 
## data:  simulationOutput
## dispersion = 1.0371, p-value = 0.664
## alternative hypothesis: two.sided
\end{verbatim}

Not significant (\(p = 0.664\)), no overdispertion detected.

\paragraph{\texorpdfstring{Model check 4: \texttt{check\_model}
overview:}{Model check 4: check\_model overview:}}\label{model-check-4-check_model-overview}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{check\_model}\NormalTok{(glmm\_gauss\_log)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `check_outliers()` does not yet support models of class `glmmTMB`.
\end{verbatim}

\pandocbounded{\includegraphics[keepaspectratio]{BIOLM0039_exam_files/figure-latex/unnamed-chunk-18-1.pdf}}

All diagnostics indicate this model suits the data well. However, the
residuals variance does seem to display slight heteroscedasticity, with
lower residuals at higher fitted values. This pattern may be due to
missing predictors which could affect higher body masses
disproportionately, although this is not a major violation of model
assumptions in this case.

\subsubsection{Fitting two further
models}\label{fitting-two-further-models}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# create gamma model (without log transformed response)}
\NormalTok{glmm\_gamma }\OtherTok{\textless{}{-}} \FunctionTok{update}\NormalTok{(glmm\_gauss\_log, }\AttributeTok{formula =}\NormalTok{ body\_mass }\SpecialCharTok{\textasciitilde{}}\NormalTok{ ., }\AttributeTok{family =} \FunctionTok{Gamma}\NormalTok{(}\AttributeTok{link =} \StringTok{"log"}\NormalTok{))}
\CommentTok{\# cube{-}root response transformed model}
\NormalTok{glmm\_gauss\_cubed }\OtherTok{\textless{}{-}} \FunctionTok{update}\NormalTok{(glmm\_gauss\_log, }\AttributeTok{formula =}\NormalTok{ (body\_mass)}\SpecialCharTok{\^{}}\NormalTok{(}\DecValTok{1}\SpecialCharTok{/}\DecValTok{3}\NormalTok{) }\SpecialCharTok{\textasciitilde{}}\NormalTok{ .)}
\end{Highlighting}
\end{Shaded}

These two models also underwent the same checks as the log Gaussian
model above, and both fit well, with diagnostics performance comparable
to \texttt{glmm\_gauss\_log}.

\subsection{6. Model testing}\label{model-testing}

\subsubsection{6.1 Model predictions
visualised}\label{model-predictions-visualised}

A visualisation of the above tests with plotting of observed mass vs
predicted mass from each model, using \texttt{modelbased}:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# get predicted data frame for each model based on the observed predictor values at each observation using predict()}
\NormalTok{models\_predictions }\OtherTok{\textless{}{-}} \FunctionTok{tibble}\NormalTok{(}
  \AttributeTok{observed =}\NormalTok{ df\_clean}\SpecialCharTok{$}\NormalTok{body\_mass,}
  \AttributeTok{predicted\_gamma =} \FunctionTok{predict}\NormalTok{(glmm\_gamma, }\AttributeTok{type =} \StringTok{"response"}\NormalTok{),}
  \AttributeTok{predicted\_gauss\_log =} \FunctionTok{exp}\NormalTok{(}\FunctionTok{predict}\NormalTok{(glmm\_gauss\_log)),}
  \AttributeTok{predicted\_gauss\_cubed =}\NormalTok{ (}\FunctionTok{predict}\NormalTok{(glmm\_gauss\_cubed))}\SpecialCharTok{\^{}}\DecValTok{3}
\NormalTok{)}

\CommentTok{\# create observed vs. predicted plot for all models:}
\NormalTok{models\_predictions }\SpecialCharTok{\%\textgreater{}\%}
  
  \FunctionTok{ggplot}\NormalTok{() }\SpecialCharTok{+}
  
  \CommentTok{\# add loess line from each model\textquotesingle{}s predictions}
  \FunctionTok{geom\_smooth}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ observed, }\AttributeTok{y =}\NormalTok{ predicted\_gamma, }\AttributeTok{colour =} \StringTok{"gamma"}\NormalTok{), }\AttributeTok{se =} \ConstantTok{FALSE}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_smooth}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ observed, }\AttributeTok{y =}\NormalTok{ predicted\_gauss\_log, }\AttributeTok{colour =} \StringTok{"gauss\_log"}\NormalTok{), }\AttributeTok{se =} \ConstantTok{FALSE}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_smooth}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ observed, }\AttributeTok{y =}\NormalTok{ predicted\_gauss\_cubed, }\AttributeTok{colour =} \StringTok{"gauss\_cubed"}\NormalTok{), }\AttributeTok{se =} \ConstantTok{FALSE}\NormalTok{) }\SpecialCharTok{+}
  
  \CommentTok{\# add slope = 1 line for observed = predicted}
  \FunctionTok{geom\_abline}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{intercept =} \DecValTok{0}\NormalTok{, }\AttributeTok{slope =} \DecValTok{1}\NormalTok{, }\AttributeTok{colour =} \StringTok{"1:1"}\NormalTok{),  }\AttributeTok{linetype =} \StringTok{"dashed"}\NormalTok{,) }\SpecialCharTok{+}  
  
  \CommentTok{\# adding a legend }
  \FunctionTok{scale\_colour\_manual}\NormalTok{(}\AttributeTok{name =} \ConstantTok{NULL}\NormalTok{,}
                     \AttributeTok{breaks =} \FunctionTok{c}\NormalTok{(}\StringTok{"gamma"}\NormalTok{, }\StringTok{"gauss\_log"}\NormalTok{, }\StringTok{"gauss\_cubed"}\NormalTok{, }\StringTok{"1:1"}\NormalTok{),}
                     \AttributeTok{labels =} \FunctionTok{c}\NormalTok{(}\StringTok{"Gamma Model"}\NormalTok{, }\StringTok{"Log Gauss Model"}\NormalTok{, }\StringTok{"Cube{-}root Gauss Model"}\NormalTok{, }\StringTok{"Predicted = Observed"}\NormalTok{),}
                     \AttributeTok{values =} \FunctionTok{c}\NormalTok{(}\FunctionTok{wes\_palette}\NormalTok{(}\StringTok{"AsteroidCity1"}\NormalTok{))) }\SpecialCharTok{+}
  
  \FunctionTok{ggtitle}\NormalTok{(}\StringTok{"Observed against Predicted Body Mass Across Models"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{ylab}\NormalTok{(}\StringTok{"Body mass (kg) {-} predicted"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{xlab}\NormalTok{(}\StringTok{"Body mass (kg) {-} observed"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme\_lucid}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{BIOLM0039_exam_files/figure-latex/unnamed-chunk-20-1.pdf}}

All models display over predicting at lower masses and under predicting
at higher masses compared to the 1:1 observed line, indicating an
inability to adequately capture the body mass variance towards extremes.
This reflects the heteroscedasticity mentioned earlier which can pull
the predicted values at high body masses back towards the mean.
Predictions towards the extremes should be taken with caution.

\subsubsection{\texorpdfstring{6.2 \texttt{ANOVA} model
comparisons}{6.2 ANOVA model comparisons}}\label{anova-model-comparisons}

As there are currently three working models which have all passed
\texttt{DHARMa} residual and \texttt{check\_model()} checks and appear
to predict very similar body masses, their fits can be directly
quanitified against each other using \texttt{anova()} with \texttt{AIC}
and \texttt{BIC} acting as comparative scores.

AIC and BIC try to balance how well a model fits with its complexity
(models with more parameters are penalised harder to avoid overfitting.
A lower score indicates a batter model in both AIC and BIC, with BIC
penalising complexity more than AIC:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{anova}\NormalTok{(glmm\_gauss\_log, glmm\_gamma, glmm\_gauss\_cubed)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Data: df_clean
## Models:
## glmm_gauss_log: log(body_mass) ~ landscape + vegetation + lion_presence + distance_to_water_km + , zi=~0, disp=~1
## glmm_gauss_log:     average_annual_rainfall_mm + predator_density_per_sq_km + , zi=~0, disp=~1
## glmm_gauss_log:     (1 | park) + (1 | observer), zi=~0, disp=~1
## glmm_gamma: body_mass ~ landscape + vegetation + lion_presence + distance_to_water_km + , zi=~0, disp=~1
## glmm_gamma:     average_annual_rainfall_mm + predator_density_per_sq_km + , zi=~0, disp=~1
## glmm_gamma:     (1 | park) + (1 | observer), zi=~0, disp=~1
## glmm_gauss_cubed: (body_mass)^(1/3) ~ landscape + vegetation + lion_presence + , zi=~0, disp=~1
## glmm_gauss_cubed:     distance_to_water_km + average_annual_rainfall_mm + predator_density_per_sq_km + , zi=~0, disp=~1
## glmm_gauss_cubed:     (1 | park) + (1 | observer), zi=~0, disp=~1
##                  Df    AIC    BIC   logLik deviance  Chisq Chi Df Pr(>Chisq)
## glmm_gauss_log   10  -48.9  -12.9    34.43    -68.9                         
## glmm_gamma       10 3763.7 3799.7 -1871.87   3743.7    0.0      0          1
## glmm_gauss_cubed 10  629.8  665.8  -304.91    609.8 3133.9      0     <2e-16
##                     
## glmm_gauss_log      
## glmm_gamma          
## glmm_gauss_cubed ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
\end{verbatim}

Despite all three models performing well in diagnostic tests, AIC and
BIC results show \texttt{glmm\_gauss\_log} scored the lowest in both and
as such will be taken forward as the candidate model.

\subsection{7. Model refining}\label{model-refining}

With \texttt{glmm\_gauss\_log} selected as the candidate model, model
parameters will next be refined and further testing will take place,
along with visualisation, to further refine the model if possible.

Another summary of \texttt{glmm\_gauss2}:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(glmm\_gauss\_log)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  Family: gaussian  ( identity )
## Formula:          
## log(body_mass) ~ landscape + vegetation + lion_presence + distance_to_water_km +  
##     average_annual_rainfall_mm + predator_density_per_sq_km +  
##     (1 | park) + (1 | observer)
## Data: df_clean
## 
##       AIC       BIC    logLik -2*log(L)  df.resid 
##     -48.9     -12.9      34.4     -68.9       259 
## 
## Random effects:
## 
## Conditional model:
##  Groups   Name        Variance Std.Dev.
##  park     (Intercept) 0.004804 0.06931 
##  observer (Intercept) 0.005935 0.07704 
##  Residual             0.042434 0.20599 
## Number of obs: 269, groups:  park, 4; observer, 5
## 
## Dispersion estimate for gaussian family (sigma^2): 0.0424 
## 
## Conditional model:
##                              Estimate Std. Error z value Pr(>|z|)    
## (Intercept)                 7.138e+00  7.814e-02   91.34   <2e-16 ***
## landscapeHilly             -4.104e-02  2.542e-02   -1.61   0.1065    
## vegetationOpen             -3.825e-02  2.547e-02   -1.50   0.1332    
## lion_presencePresent        1.957e-02  2.599e-02    0.75   0.4515    
## distance_to_water_km        1.127e-02  5.123e-03    2.20   0.0279 *  
## average_annual_rainfall_mm -5.725e-05  4.409e-05   -1.30   0.1941    
## predator_density_per_sq_km -5.923e-04  1.074e-02   -0.06   0.9560    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
\end{verbatim}

\subsubsection{7.1 Model simplifying}\label{model-simplifying}

From the summary above only \texttt{distance\_to\_water\_km} is a
significant predictor in giraffe body mass in this model
(\(p = 0.279\)), and there are two highly non-significant predictors:
\texttt{predator\_density\_per\_sq\_km} (\(p = 0.956\)) and
\texttt{lion\_presencePresent} (\(p = 0.452\)). Also, the coefficient
for average rainfall is so small (\(\approx\) 5.7e-5) it's negligible in
this model and will be removed.

A model will be made without these three predictors to test if reducing
complexity still produces a valid model:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# update candidate model to remove the lion/predator and rainfall predictors:}
\NormalTok{glmm\_gauss2\_log }\OtherTok{\textless{}{-}} \FunctionTok{update}\NormalTok{(glmm\_gauss\_log, }\AttributeTok{formula. =}\NormalTok{ . }\SpecialCharTok{\textasciitilde{}}\NormalTok{ . }\SpecialCharTok{{-}}\NormalTok{ average\_annual\_rainfall\_mm }\SpecialCharTok{{-}}\NormalTok{ lion\_presence }\SpecialCharTok{{-}}\NormalTok{ predator\_density\_per\_sq\_km)}

\CommentTok{\# check model summary:}
 \FunctionTok{summary}\NormalTok{(glmm\_gauss2\_log)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  Family: gaussian  ( identity )
## Formula:          
## log(body_mass) ~ landscape + vegetation + distance_to_water_km +  
##     (1 | park) + (1 | observer)
## Data: df_clean
## 
##       AIC       BIC    logLik -2*log(L)  df.resid 
##     -52.3     -27.1      33.1     -66.3       262 
## 
## Random effects:
## 
## Conditional model:
##  Groups   Name        Variance Std.Dev.
##  park     (Intercept) 0.004758 0.06898 
##  observer (Intercept) 0.005897 0.07679 
##  Residual             0.042867 0.20704 
## Number of obs: 269, groups:  park, 4; observer, 5
## 
## Dispersion estimate for gaussian family (sigma^2): 0.0429 
## 
## Conditional model:
##                       Estimate Std. Error z value Pr(>|z|)    
## (Intercept)           7.089202   0.056246  126.04   <2e-16 ***
## landscapeHilly       -0.040798   0.025448   -1.60   0.1089    
## vegetationOpen       -0.039043   0.025554   -1.53   0.1265    
## distance_to_water_km  0.011502   0.005116    2.25   0.0246 *  
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
\end{verbatim}

Look at tidy summary of effects:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{broom.mixed}\SpecialCharTok{::}\FunctionTok{tidy}\NormalTok{(glmm\_gauss2\_log, }\AttributeTok{conf.int =} \ConstantTok{TRUE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 7 x 10
##   effect   component group   term  estimate std.error statistic p.value conf.low
##   <chr>    <chr>     <chr>   <chr>    <dbl>     <dbl>     <dbl>   <dbl>    <dbl>
## 1 fixed    cond      <NA>    (Int~   7.09     0.0562     126.    0       6.98   
## 2 fixed    cond      <NA>    land~  -0.0408   0.0254      -1.60  0.109  -0.0907 
## 3 fixed    cond      <NA>    vege~  -0.0390   0.0256      -1.53  0.127  -0.0891 
## 4 fixed    cond      <NA>    dist~   0.0115   0.00512      2.25  0.0246  0.00147
## 5 ran_pars cond      park    sd__~   0.0690  NA           NA    NA       0.190  
## 6 ran_pars cond      observ~ sd__~   0.0768  NA           NA    NA      NA      
## 7 ran_pars cond      Residu~ sd__~   0.207   NA           NA    NA      NA      
## # i 1 more variable: conf.high <dbl>
\end{verbatim}

Comparing \texttt{glmm\_gauss\_log} and \texttt{glmm\_gauss2\_log} with
ANOVA:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{anova}\NormalTok{(glmm\_gauss\_log, glmm\_gauss2\_log)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Data: df_clean
## Models:
## glmm_gauss2_log: log(body_mass) ~ landscape + vegetation + distance_to_water_km + , zi=~0, disp=~1
## glmm_gauss2_log:     (1 | park) + (1 | observer), zi=~0, disp=~1
## glmm_gauss_log: log(body_mass) ~ landscape + vegetation + lion_presence + distance_to_water_km + , zi=~0, disp=~1
## glmm_gauss_log:     average_annual_rainfall_mm + predator_density_per_sq_km + , zi=~0, disp=~1
## glmm_gauss_log:     (1 | park) + (1 | observer), zi=~0, disp=~1
##                 Df     AIC     BIC logLik deviance  Chisq Chi Df Pr(>Chisq)
## glmm_gauss2_log  7 -52.258 -27.095 33.129  -66.258                         
## glmm_gauss_log  10 -48.865 -12.918 34.432  -68.865 2.6073      3     0.4562
\end{verbatim}

Removing the above fixed effects did not significantly worsen the model
fit (\(p = 0.456\)), and the lower AIC/BIC vales mean this model is
preferred for parsimony, even at the slightly reduced `biological
completeness' of the model from removing predictors.

Check model residuals with DHARMa, and \texttt{check\_model()}:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# simulate residuals with 1000 simulations:}
\NormalTok{glmm\_gauss2\_log\_res }\OtherTok{\textless{}{-}} \FunctionTok{simulateResiduals}\NormalTok{(glmm\_gauss2\_log, }\AttributeTok{n =} \DecValTok{1000}\NormalTok{)}
\FunctionTok{plot}\NormalTok{(glmm\_gauss2\_log\_res)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{BIOLM0039_exam_files/figure-latex/unnamed-chunk-26-1.pdf}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{check\_model}\NormalTok{(glmm\_gauss2\_log)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `check_outliers()` does not yet support models of class `glmmTMB`.
\end{verbatim}

\pandocbounded{\includegraphics[keepaspectratio]{BIOLM0039_exam_files/figure-latex/unnamed-chunk-27-1.pdf}}

Still passes residual testing and other diagnostics, and still
displaying slight heteroscedasticity in residuals, although this is not
a significant violation of model assumptions.

\subsubsection{7.2 Testing interactions}\label{testing-interactions}

Interactions with vegetation/landscape will be assessed to see if the
effect of distance to water varies among habitat types, and to see if
model fit improves by their inclusion:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# distance to water to vegetation:}
\NormalTok{glmm\_gauss3\_log }\OtherTok{\textless{}{-}} \FunctionTok{update}\NormalTok{(glmm\_gauss2\_log, . }\SpecialCharTok{\textasciitilde{}}\NormalTok{ . }\SpecialCharTok{+}\NormalTok{ distance\_to\_water\_km}\SpecialCharTok{:}\NormalTok{vegetation)}

\CommentTok{\#distance to water to landscape:}
\NormalTok{glmm\_gauss4\_log }\OtherTok{\textless{}{-}} \FunctionTok{update}\NormalTok{(glmm\_gauss2\_log, . }\SpecialCharTok{\textasciitilde{}}\NormalTok{ . }\SpecialCharTok{+}\NormalTok{ distance\_to\_water\_km}\SpecialCharTok{:}\NormalTok{landscape)}

\CommentTok{\# test against current model}
\FunctionTok{anova}\NormalTok{(glmm\_gauss2\_log, glmm\_gauss3\_log, glmm\_gauss4\_log)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Data: df_clean
## Models:
## glmm_gauss2_log: log(body_mass) ~ landscape + vegetation + distance_to_water_km + , zi=~0, disp=~1
## glmm_gauss2_log:     (1 | park) + (1 | observer), zi=~0, disp=~1
## glmm_gauss3_log: log(body_mass) ~ landscape + vegetation + distance_to_water_km + , zi=~0, disp=~1
## glmm_gauss3_log:     (1 | park) + (1 | observer) + vegetation:distance_to_water_km, zi=~0, disp=~1
## glmm_gauss4_log: log(body_mass) ~ landscape + vegetation + distance_to_water_km + , zi=~0, disp=~1
## glmm_gauss4_log:     (1 | park) + (1 | observer) + landscape:distance_to_water_km, zi=~0, disp=~1
##                 Df     AIC     BIC logLik deviance Chisq Chi Df Pr(>Chisq)
## glmm_gauss2_log  7 -52.258 -27.095 33.129  -66.258                        
## glmm_gauss3_log  8 -51.172 -22.414 33.586  -67.172 0.914      1      0.339
## glmm_gauss4_log  8 -50.960 -22.203 33.480  -66.960 0.000      0      1.000
\end{verbatim}

Adding these interactions did not significantly improve model fit
(\(p = 0.339\) and \(1.00\)), and the slightly reduced deviance in
\texttt{glmm\_gauss3\_log} does not justify the increased complexity and
AIC/BIC scores. As such the more parsimonious \texttt{glmm\_gauss2\_log}
model will be taking forward as the final model.

\subsection{8. Model fit and
interpretation}\label{model-fit-and-interpretation}

This model predictions can be plotted against the observed values to
visualise how well it fits the observed data:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# create predicted and observed data frame to get predicted values for mass from the model based on the predictor values at each true observation:}
\NormalTok{fit\_model\_gauss2\_log }\OtherTok{\textless{}{-}} \FunctionTok{data.frame}\NormalTok{(}
  
  \CommentTok{\# back transform from log to get predicted on the correct scale:}
  \StringTok{"Predicted"} \OtherTok{=} \FunctionTok{exp}\NormalTok{(}\FunctionTok{predict}\NormalTok{(glmm\_gauss2\_log)),}
  \StringTok{"Observed"} \OtherTok{=}\NormalTok{ df\_clean}\SpecialCharTok{$}\NormalTok{body\_mass}
  
\NormalTok{)}

\CommentTok{\# plot predicted vs observed with 1:1 (observed:observed) comparison line}
\FunctionTok{ggplot}\NormalTok{(fit\_model\_gauss2\_log) }\SpecialCharTok{+}
  
  \CommentTok{\# each point (x) = observed, (y) = model prediction}
  \FunctionTok{geom\_point}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ Observed, }\AttributeTok{y =}\NormalTok{ Predicted,)) }\SpecialCharTok{+}
  
  \CommentTok{\# add loess line of observed:predicted from the model}
  \FunctionTok{geom\_smooth}\NormalTok{(}
    \FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ Observed, }\AttributeTok{y =}\NormalTok{ Predicted, }\AttributeTok{colour =} \StringTok{"gauss"}\NormalTok{),}
    \AttributeTok{method =}\NormalTok{ loess,}
    \AttributeTok{se =} \ConstantTok{FALSE}\NormalTok{) }\SpecialCharTok{+}
  
  \CommentTok{\# add slope = 1 line for observed = predicted}
  \FunctionTok{geom\_abline}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{intercept =} \DecValTok{0}\NormalTok{, }\AttributeTok{slope =} \DecValTok{1}\NormalTok{, }\AttributeTok{colour =} \StringTok{"1:1"}\NormalTok{),  }\AttributeTok{linetype =} \StringTok{"dashed"}\NormalTok{,) }\SpecialCharTok{+}

  \CommentTok{\# aesthetics}
  \FunctionTok{scale\_colour\_manual}\NormalTok{(}\AttributeTok{name =} \ConstantTok{NULL}\NormalTok{,}
                      \AttributeTok{breaks =} \FunctionTok{c}\NormalTok{(}\StringTok{"1:1"}\NormalTok{, }\StringTok{"gauss"}\NormalTok{),}
                      \AttributeTok{labels =} \FunctionTok{c}\NormalTok{(}\StringTok{"Observed = Predicted"}\NormalTok{, }\StringTok{"Log Gauss2 Model"}\NormalTok{),}
                      \AttributeTok{values =} \FunctionTok{c}\NormalTok{(}\StringTok{"black"}\NormalTok{, }\FunctionTok{wes\_palette}\NormalTok{(}\StringTok{"AsteroidCity3"}\NormalTok{)[}\DecValTok{1}\NormalTok{])) }\SpecialCharTok{+}
  
  \FunctionTok{xlab}\NormalTok{(}\StringTok{"Body mass (observed)"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{ylab}\NormalTok{(}\StringTok{"Body mass (predicted)"}\NormalTok{) }\SpecialCharTok{+}
  
  \FunctionTok{ggtitle}\NormalTok{(}\StringTok{"Predicted vs. Observed Giraffe Body Mass for Log Gauss2 Model"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme\_lucid}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{BIOLM0039_exam_files/figure-latex/unnamed-chunk-29-1.pdf}}

Points represent the predicted mass value from the
\texttt{glmm\_gauss2\_log} model based on the predictor values from the
true observations in the data, with a 1:1 observed line for reference to
observed values. The fitted loess line shows that the model tends to
over predicts lower body masses, and under predict higher body masses
compared to the observed values which could be due to missing predictors
in the data as mentioned above, however overall residuals and model
checks indicate a good fit. As the main aim is to test any significant
predictors on body mass, this model is appropriate.

\paragraph{Mean absolute error (MAE)}\label{mean-absolute-error-mae}

MAE shows the average average difference in observed vs.~predicted body
mass from the model, and is used to see how far the model predictions
differ from the observed on average:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# using fit\_model\_gauss2\_log to calculate MAE using absolute residuals:}
\NormalTok{mae\_glmm\_gauss2\_log }\OtherTok{\textless{}{-}} \FunctionTok{mean}\NormalTok{(}\FunctionTok{abs}\NormalTok{(fit\_model\_gauss2\_log}\SpecialCharTok{$}\NormalTok{Observed }\SpecialCharTok{{-}}\NormalTok{ fit\_model\_gauss2\_log}\SpecialCharTok{$}\NormalTok{Predicted))}
\NormalTok{mae\_glmm\_gauss2\_log}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 194.2842
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# and as a percentage of the observed mean:}
\NormalTok{(mae\_glmm\_gauss2\_log}\SpecialCharTok{/}\FunctionTok{mean}\NormalTok{(df\_clean}\SpecialCharTok{$}\NormalTok{body\_mass))}\SpecialCharTok{*}\DecValTok{100}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 15.74403
\end{verbatim}

From this, the model predicts giraffe body mass with an MAE of 194.3kg
(15.7\% of mean mass) observed body mass, indicating reasonable, but not
high, prediction accuracy.

\paragraph{Variance in model and residual
error}\label{variance-in-model-and-residual-error}

Variance in the observed response (log(body mass)) captured by the model
vs.~residual error can be quantified using \texttt{r2\_nakagawa()} from
\texttt{performance}:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{r2\_nakagawa}\NormalTok{(glmm\_gauss2\_log)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # R2 for Mixed Models
## 
##   Conditional R2: 0.221
##      Marginal R2: 0.027
\end{verbatim}

From this, the conditional r-squared (random and fixed effects in the
model) only capture 22.1\% of the variance, with marginal r-squared
(fixed effects only) capturing 2.7\% of the variance. Therefore the
random effects account for about 19.5\% of the variance in the response.

This means that the remaining 77.9\% of the variance cannot be explained
by the model which could be caused by differences not accounted for by
the chosen predictors, or other biological factors not included in the
model. This is quite a large amount of variance to be unexplained by the
model, and is possibly due to missing other predictors in the data.
Missing a significant amount of data which could impact giraffe body
mass reduces a model's prediction capabilities, and therefore decreases
the amount of variance in the response which can be explained by the
model.

\subsection{9. Model equation and predictor
significance}\label{model-equation-and-predictor-significance}

Exact coefficients are not strictly necessary as the main aim is to
assess which factors significantly impact giraffe body mass, but it can
be helpful to explicitly understand the model in log linear and back
transformed forms.

\subsubsection{9.1 Model equation}\label{model-equation}

Summary of \texttt{glmm\_gauss2\_log}:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(glmm\_gauss2\_log)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  Family: gaussian  ( identity )
## Formula:          
## log(body_mass) ~ landscape + vegetation + distance_to_water_km +  
##     (1 | park) + (1 | observer)
## Data: df_clean
## 
##       AIC       BIC    logLik -2*log(L)  df.resid 
##     -52.3     -27.1      33.1     -66.3       262 
## 
## Random effects:
## 
## Conditional model:
##  Groups   Name        Variance Std.Dev.
##  park     (Intercept) 0.004758 0.06898 
##  observer (Intercept) 0.005897 0.07679 
##  Residual             0.042867 0.20704 
## Number of obs: 269, groups:  park, 4; observer, 5
## 
## Dispersion estimate for gaussian family (sigma^2): 0.0429 
## 
## Conditional model:
##                       Estimate Std. Error z value Pr(>|z|)    
## (Intercept)           7.089202   0.056246  126.04   <2e-16 ***
## landscapeHilly       -0.040798   0.025448   -1.60   0.1089    
## vegetationOpen       -0.039043   0.025554   -1.53   0.1265    
## distance_to_water_km  0.011502   0.005116    2.25   0.0246 *  
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
\end{verbatim}

From this model summary \texttt{glmm\_gauss2\_log} can be expressed
as:\\
\[
\text{log(Body Mass}_{i}\text{(kg))} = \beta_0 + \beta_1\text{Landscape}_{i} + \beta_2\text{Vegetation}_{i} + \beta_3\text{Distance to Water}_{i} + b_{park[i]} + b_{observer[i]} + \epsilon_{i}
\tag{1}
\]

Where:

\begin{itemize}
\tightlist
\item
  \(i\) represents the observation
\item
  \(\beta_0\) is the expected body mass when all other predictors are at
  reference level or mean values.\\
\item
  \(\beta\) values are the model variable coefficients\\
\item
  \(\text{Landscape}_{i}\) -\textgreater{} BOOL landscape value: hilly
  (=1) or flat (=0)\\
\item
  \(\text{Vegetation}_{i}\) -\textgreater{} BOOL vegetation value: open
  (=1) or dense (=0)\\
\item
  \(\text{Distance to Water}_{i}\) is the distance to water (km)
\item
  \(b_{park[i]}\) is the intercept shift for park in observation \(i\)\\
\item
  \(b_{observer[i]}\) is the intercept shift for observer in observation
  \(i\)\\
\item
  \(\epsilon_{i}\) is the error term (the unexplained 77.9\% of
  variance)
\end{itemize}

With coefficients: \[
\text{log(Body Mass}_{i}\text{(kg))} = 7.09 - 0.041\cdot\text{Landscape}_{i}\text{} - 0.039\cdot\text{Vegetation}_{i} + 0.012\cdot\text{Distance to Water}_{i}\text{(km)} + b_{park[i]} + b_{observer[i]} + \epsilon_{i}
\]

\subsubsection{9.2 Back transformation}\label{back-transformation}

Back transformation gets from log (natural) to the normal scale:

\[
\text{Body Mass}_{i}\text{(kg)} = e^{7.09 - 0.041\cdot\text{Landscape}_{i}\text{} - 0.039\cdot\text{Vegetation}_{i} + 0.012\cdot\text{Distance to Water}_{i}\text{(km)} + b_{park[i]} + b_{observer[i]} + \epsilon_{i}}
\]

On this scale, the predictors now have multiplicative, rather than
additive, effects on the body mass in this model. In other words a
predictor with coefficient \(\beta\) in the log scale now has a
multiplicative effect of \(e^{x\beta}\) on body mass for an \(x\) unit
increase in that continuous predictor (or \(e^\beta\) vs.~\(1\) for the
categorical predictors), all other effects constant.

\subsubsection{9.3 Significant predictor: distance from
water}\label{significant-predictor-distance-from-water}

This model suggests that the only significant predictor on giraffe body
mass at the 5\% significance level is the Distance from water
(\(p = 0.025\)). The effect of this predictor in the model is:

\[
\text{Body Mass}_i\text{(kg)} \propto e^{0.012\cdot\text{Distance to Water}_{i}\text{(km)}} \approx 1.012^{\text{Distance to Water (km)}}
\]

So the model predicts a small marginal effect: giraffe mass increases by
\(\approx\) 1.2\% for every km further from water the giraffe is when
observed, all other predictors constant, and at a significance of
\(p = 0.025\).

\subsection{10. Interpreting model fixed
effects}\label{interpreting-model-fixed-effects}

The fixed effects in \texttt{glmm\_gauss2\_log} can be plotted in terms
of their effects on giraffe body mass with confidence intervals (CI) at
95\%:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# data frame with fixed effect and confidence intervals:}
\NormalTok{model\_fixed\_effects\_tidy }\OtherTok{\textless{}{-}}\NormalTok{ broom.mixed}\SpecialCharTok{::}\FunctionTok{tidy}\NormalTok{(glmm\_gauss2\_log, }\AttributeTok{conf.int =} \ConstantTok{TRUE}\NormalTok{, }\AttributeTok{conf.level =} \FloatTok{0.95}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
  
  \CommentTok{\# don\textquotesingle{}t include random effects (see next section):}
  \FunctionTok{filter}\NormalTok{(effect }\SpecialCharTok{==} \StringTok{"fixed"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
  
  \CommentTok{\# remove intercept value}
  \FunctionTok{filter}\NormalTok{(term}\SpecialCharTok{!=}\StringTok{"(Intercept)"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

Plotting these data:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# plot fixed effect coefficients}
\FunctionTok{ggplot}\NormalTok{(model\_fixed\_effects\_tidy, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x=}\NormalTok{estimate, }\AttributeTok{y=}\NormalTok{term)) }\SpecialCharTok{+} 
  
  \CommentTok{\# add fixed effect coefficient}
  \FunctionTok{geom\_point}\NormalTok{(}\AttributeTok{shape =} \DecValTok{21}\NormalTok{, }\AttributeTok{fill =} \FunctionTok{wes\_palette}\NormalTok{(}\StringTok{"FantasticFox1"}\NormalTok{)[}\DecValTok{2}\NormalTok{], }\AttributeTok{size =} \DecValTok{5}\NormalTok{)}\SpecialCharTok{+}
  
  \CommentTok{\# 95\% CI error bars}
  \FunctionTok{geom\_errorbar}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{xmin=}\NormalTok{conf.low, }\AttributeTok{xmax=}\NormalTok{conf.high), }\AttributeTok{width =} \FloatTok{0.25}\NormalTok{, }\AttributeTok{col=}\StringTok{"grey50"}\NormalTok{) }\SpecialCharTok{+}
  
  \CommentTok{\# red dashed line at x = 0}
  \FunctionTok{geom\_vline}\NormalTok{(}\AttributeTok{xintercept =}\DecValTok{0}\NormalTok{, }\AttributeTok{linetype =} \StringTok{"dashed"}\NormalTok{, }\AttributeTok{col =} \StringTok{"red"}\NormalTok{) }\SpecialCharTok{+}
  
  \CommentTok{\# aesthetics}
  \FunctionTok{xlab}\NormalTok{(}\StringTok{"Coefficient estimate on log(body mass) scale"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{ylab}\NormalTok{(}\StringTok{"Fixed effect"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{ggtitle}\NormalTok{(}\StringTok{"Estimated Model Fixed Effect Coefficients at 95\% CI"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme\_lucid}\NormalTok{() }
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{BIOLM0039_exam_files/figure-latex/unnamed-chunk-34-1.pdf}}

These plotted coefficient estimates with 95\% CI show the estimates
impact on log(body mass) of each fixed effect in the model. The red line
at x = 0 indicates \(\beta = 0\) so no effect on log(body mass), (ie. a
multiplicative effect of \(e^{0} = 1\) on body mass). Distance to water
displays non-overlap with this line which displays its significance at

Visual of the statistically significant predictor against body mass:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# retrieve back transormed predicted data frame using ggpredict at 95\% CI}
\NormalTok{df\_predict }\OtherTok{\textless{}{-}} \FunctionTok{ggpredict}\NormalTok{(glmm\_gauss2\_log, }\AttributeTok{terms =} \FunctionTok{c}\NormalTok{(}\StringTok{"distance\_to\_water\_km"}\NormalTok{), }\AttributeTok{ci\_level =} \FloatTok{0.95}\NormalTok{, }\AttributeTok{back\_transform =} \ConstantTok{TRUE}\NormalTok{)}

\CommentTok{\# plot predictions for distance to water}
\FunctionTok{plot}\NormalTok{(df\_predict) }\SpecialCharTok{+}
  
  \CommentTok{\# overlay observed data}
  \FunctionTok{geom\_point}\NormalTok{(}\AttributeTok{data =}\NormalTok{ df\_clean, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ distance\_to\_water\_km, }\AttributeTok{y =}\NormalTok{ body\_mass), }\AttributeTok{alpha =} \FloatTok{0.5}\NormalTok{, }\AttributeTok{color =} \FunctionTok{wes\_palette}\NormalTok{(}\StringTok{"Moonrise2"}\NormalTok{)[}\DecValTok{1}\NormalTok{]) }\SpecialCharTok{+}
  
  \CommentTok{\# aesthetics}
  \FunctionTok{xlab}\NormalTok{(}\StringTok{"Distance to Water (km)"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{ylab}\NormalTok{(}\StringTok{"Body Mass (kg)"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{ggtitle}\NormalTok{(}\StringTok{"Predicted Body Mass against Distance to Water with 95\% CIs (other predictors constant)"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme\_lucid}\NormalTok{() }\SpecialCharTok{+} 
  \FunctionTok{geom\_line}\NormalTok{(}\AttributeTok{color =} \FunctionTok{wes\_palette}\NormalTok{(}\StringTok{"Moonrise2"}\NormalTok{)[}\DecValTok{2}\NormalTok{], }\AttributeTok{linewidth =} \FloatTok{1.25}\NormalTok{) }
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{BIOLM0039_exam_files/figure-latex/unnamed-chunk-35-1.pdf}}

The points above are the observed data overlaid on the model's
prediction for body mass against distance to water. This plot is
exponential on this normal scale with
\(\text{Body Mass} \propto 1.012^{\text{Distance to Water}}\) but
approximates linear over this range as the coefficient is small (1.2\%
increase per unit distance).

\subsection{11. Interpreting model random
effects}\label{interpreting-model-random-effects}

From the above equation for \texttt{glmm\_gauss2\_log} (equation 1),
there are random effects termed \(b_{park[i]}\) and \(b_{observer[i]}\).
These are estimated multiplicative factors \(e^{b_{park[i]}}\) and
\(e^{b_{observer[i]}}\) (on the original scale) from the expected
population level body mass, and they represent deviations in body mass
purely due to the level of the random effect, assuming fixed effects are
constant.

To visualise the estimated multiplicative effect for each level,
\texttt{ranef()} from \texttt{glmmTMB} will be used to extract random
effects (park and observer):

\subsubsection{11.1 Park}\label{park}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# extract park random effects  with condVar attributes attached (as a list):}
\NormalTok{ranefs }\OtherTok{\textless{}{-}} \FunctionTok{ranef}\NormalTok{(glmm\_gauss2\_log, }\AttributeTok{condVar =} \ConstantTok{TRUE}\NormalTok{)}

\CommentTok{\# ranef contains the data frames within $cond, so to extract and mutate park df:}
\NormalTok{ranefs\_park }\OtherTok{\textless{}{-}}\NormalTok{ ranefs}\SpecialCharTok{$}\NormalTok{cond}\SpecialCharTok{$}\NormalTok{park }\SpecialCharTok{\%\textgreater{}\%}
  
  \FunctionTok{mutate}\NormalTok{(}
    \CommentTok{\# make each row name a factored column for the data frames}
    \AttributeTok{park =} \FunctionTok{factor}\NormalTok{(}\FunctionTok{rownames}\NormalTok{(.)),}
    
    \CommentTok{\# back transform the intercept to get on the normal scale}
    \AttributeTok{bt =} \FunctionTok{exp}\NormalTok{(}\StringTok{\textasciigrave{}}\AttributeTok{(Intercept)}\StringTok{\textasciigrave{}}\NormalTok{),}
    
    \CommentTok{\# extract conditional variance from the 3d array it is stored in in this df:}
    \AttributeTok{condVar =} \FunctionTok{attr}\NormalTok{(., }\StringTok{"condVar"}\NormalTok{)[}\DecValTok{1}\NormalTok{, }\DecValTok{1}\NormalTok{, ],}
    
    \CommentTok{\# calculate (log) standard errors from condVar:}
    \AttributeTok{se =} \FunctionTok{sqrt}\NormalTok{(condVar),}
  
    \CommentTok{\# back transform and add upper and lower bounds at 95\% confidence intervals (1.96 x se)}
    \AttributeTok{bt\_lower =} \FunctionTok{exp}\NormalTok{(}\StringTok{\textasciigrave{}}\AttributeTok{(Intercept)}\StringTok{\textasciigrave{}} \SpecialCharTok{{-}} \FloatTok{1.96}\SpecialCharTok{*}\NormalTok{se),}
    \AttributeTok{bt\_upper =} \FunctionTok{exp}\NormalTok{(}\StringTok{\textasciigrave{}}\AttributeTok{(Intercept)}\StringTok{\textasciigrave{}} \SpecialCharTok{+} \FloatTok{1.96}\SpecialCharTok{*}\NormalTok{se)}
\NormalTok{  )}

\FunctionTok{head}\NormalTok{(ranefs\_park)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                           (Intercept)                    park        bt
## Golden Tusk Safari       0.0004860934      Golden Tusk Safari 1.0004862
## Lionshade Wilderness    -0.0510471832    Lionshade Wilderness 0.9502338
## Savanna Whisper Reserve -0.0485490438 Savanna Whisper Reserve 0.9526106
## Zebra Horizon Park       0.0991101089      Zebra Horizon Park 1.1041879
##                             condVar         se  bt_lower bt_upper
## Golden Tusk Safari      0.001587330 0.03984131 0.9253318 1.081745
## Lionshade Wilderness    0.001685555 0.04105551 0.8767653 1.029859
## Savanna Whisper Reserve 0.001670796 0.04087538 0.8792687 1.032070
## Zebra Horizon Park      0.001691993 0.04113384 1.0186597 1.196897
\end{verbatim}

Now the data frame has the necessary estimated multiplicative factors
(\texttt{bt}) for each level, they can be plotted along with the errors
for each estimate. Note these factors are equivalent to
\(e^{b_{park[i]}}\) due to back transformation.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# plot park random effect impact on body mass }

\FunctionTok{ggplot}\NormalTok{(ranefs\_park, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ bt, }\AttributeTok{y =}\NormalTok{ park)) }\SpecialCharTok{+}
  
  \FunctionTok{geom\_point}\NormalTok{(}\AttributeTok{col =} \StringTok{"\#F89C74"}\NormalTok{, }\AttributeTok{size =} \DecValTok{5}\NormalTok{) }\SpecialCharTok{+} 
  
  \CommentTok{\# 95\%CI error bars:}
  \FunctionTok{geom\_errorbar}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{xmin =}\NormalTok{ bt\_lower, }\AttributeTok{xmax =}\NormalTok{ bt\_upper), }\AttributeTok{width =} \FloatTok{0.25}\NormalTok{, }\AttributeTok{col =} \StringTok{"grey50"}\NormalTok{) }\SpecialCharTok{+}
  
  \CommentTok{\# add vertical line for mean/expected across all parks}
  \FunctionTok{geom\_vline}\NormalTok{(}\AttributeTok{xintercept =} \DecValTok{1}\NormalTok{, }\AttributeTok{col =}\StringTok{"red3"}\NormalTok{, }\AttributeTok{linetype =} \StringTok{"dashed"}\NormalTok{) }\SpecialCharTok{+}
  
  \FunctionTok{ylab}\NormalTok{(}\StringTok{"Park"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{xlab}\NormalTok{(}\StringTok{"Multiplicative factor on body mass "}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{ggtitle}\NormalTok{(}\StringTok{"Estimated Impact of Park (Random Effect) on Body Mass at 95\% CI"}\NormalTok{) }\SpecialCharTok{+}
  
  \FunctionTok{theme\_lucid}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{BIOLM0039_exam_files/figure-latex/unnamed-chunk-37-1.pdf}}

Error bars here represent a 95\% CI after back transforming, and the red
dashed line represents the population level expectation on the
multiplicative scale after accounting for the fixed effects (x = 1
represents no effect on the multiplicative scale for body mass).

Park multiplicative factors, at 95\% CI, range from \textasciitilde0.88
to \textasciitilde1.20, and indicate that some parks have a higher/lower
baseline body mass. Confidence intervals indicate Zebra Horizon Park
masses are \textasciitilde10\% higher than the expected population value
(factor 1.10 {[}CI: 1.02 - 1.20{]}).

To assess whether park random effects contribute significantly to this
model, a model without the parks will be fitted and then compared to
\texttt{glmm\_gauss2\_log} with anova:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# new model without park random effect:}
\NormalTok{glmm\_no\_park }\OtherTok{\textless{}{-}} \FunctionTok{update}\NormalTok{(glmm\_gauss2\_log, }\SpecialCharTok{\textasciitilde{}}\NormalTok{ . }\SpecialCharTok{{-}}\NormalTok{ (}\DecValTok{1} \SpecialCharTok{|}\NormalTok{ park))}
\CommentTok{\# compare with anova:}
\FunctionTok{anova}\NormalTok{(glmm\_gauss2\_log, glmm\_no\_park)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Data: df_clean
## Models:
## glmm_no_park: log(body_mass) ~ landscape + vegetation + distance_to_water_km + , zi=~0, disp=~1
## glmm_no_park:     (1 | observer), zi=~0, disp=~1
## glmm_gauss2_log: log(body_mass) ~ landscape + vegetation + distance_to_water_km + , zi=~0, disp=~1
## glmm_gauss2_log:     (1 | park) + (1 | observer), zi=~0, disp=~1
##                 Df     AIC     BIC logLik deviance Chisq Chi Df Pr(>Chisq)    
## glmm_no_park     6 -36.258 -14.690 24.129  -48.258                            
## glmm_gauss2_log  7 -52.258 -27.095 33.129  -66.258    18      1   2.21e-05 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
\end{verbatim}

The above shows higher AIC/BIC values without the park, and a very
significant chi squared value (\(p = 2.21e-5\)). This indicates
meaningful body mass variation across parks and its inclusion improves
model fit.

\paragraph{11.2 Observer}\label{observer}

And for the observer random effect, the same is done:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# and for observer (same as park above):}
\NormalTok{ranefs\_observer }\OtherTok{\textless{}{-}}\NormalTok{ ranefs}\SpecialCharTok{$}\NormalTok{cond}\SpecialCharTok{$}\NormalTok{observer }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}
    \AttributeTok{observer =} \FunctionTok{factor}\NormalTok{((}\FunctionTok{rownames}\NormalTok{(.))),}
    \AttributeTok{bt =} \FunctionTok{exp}\NormalTok{(}\StringTok{\textasciigrave{}}\AttributeTok{(Intercept)}\StringTok{\textasciigrave{}}\NormalTok{),}
    \AttributeTok{condVar =} \FunctionTok{attr}\NormalTok{(., }\StringTok{"condVar"}\NormalTok{)[}\DecValTok{1}\NormalTok{, }\DecValTok{1}\NormalTok{, ],}
    \AttributeTok{se =} \FunctionTok{sqrt}\NormalTok{(condVar),}
    \AttributeTok{bt\_lower =} \FunctionTok{exp}\NormalTok{(}\StringTok{\textasciigrave{}}\AttributeTok{(Intercept)}\StringTok{\textasciigrave{}} \SpecialCharTok{{-}} \FloatTok{1.96}\SpecialCharTok{*}\NormalTok{se),}
    \AttributeTok{bt\_upper =} \FunctionTok{exp}\NormalTok{(}\StringTok{\textasciigrave{}}\AttributeTok{(Intercept)}\StringTok{\textasciigrave{}} \SpecialCharTok{+} \FloatTok{1.96}\SpecialCharTok{*}\NormalTok{se)}
\NormalTok{  )}


\FunctionTok{head}\NormalTok{(ranefs\_observer)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##       (Intercept) observer        bt     condVar         se  bt_lower  bt_upper
## Obs_1  0.09452833    Obs_1 1.0991403 0.001897960 0.04356559 1.0091817 1.1971179
## Obs_2 -0.09590838    Obs_2 0.9085473 0.001777101 0.04215568 0.8364960 0.9868046
## Obs_3 -0.02598503    Obs_3 0.9743497 0.001785142 0.04225094 0.8969126 1.0584725
## Obs_4  0.06003591    Obs_4 1.0618747 0.001755430 0.04189785 0.9781582 1.1527561
## Obs_5 -0.03267086    Obs_5 0.9678571 0.001757021 0.04191683 0.8915196 1.0507310
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# plot observer random effect impact on body mass }
\FunctionTok{ggplot}\NormalTok{(ranefs\_observer, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ bt, }\AttributeTok{y =}\NormalTok{ observer)) }\SpecialCharTok{+}
  
  \FunctionTok{geom\_point}\NormalTok{(}\AttributeTok{col =} \StringTok{"\#154360"}\NormalTok{, }\AttributeTok{size =} \DecValTok{5}\NormalTok{) }\SpecialCharTok{+} 
  
  \CommentTok{\# 95\%CI error bars:}
  \FunctionTok{geom\_errorbar}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{xmin =}\NormalTok{ bt\_lower, }\AttributeTok{xmax =}\NormalTok{ bt\_upper), }\AttributeTok{width =} \FloatTok{0.25}\NormalTok{, }\AttributeTok{col =} \StringTok{"grey50"}\NormalTok{) }\SpecialCharTok{+}
  
  \CommentTok{\# add vertical line for mean/expected across all observers}
  \FunctionTok{geom\_vline}\NormalTok{(}\AttributeTok{xintercept =} \DecValTok{1}\NormalTok{, }\AttributeTok{col =}\StringTok{"red3"}\NormalTok{, }\AttributeTok{linetype =} \StringTok{"dashed"}\NormalTok{) }\SpecialCharTok{+}
  
  \FunctionTok{ylab}\NormalTok{(}\StringTok{"Observer"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{xlab}\NormalTok{(}\StringTok{"Multiplicative factor on body mass"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{ggtitle}\NormalTok{(}\StringTok{"Estimated Impact of Observer (Random Effect) on Body Mass at 95\% CI"}\NormalTok{) }\SpecialCharTok{+}
  
  \FunctionTok{theme\_lucid}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{BIOLM0039_exam_files/figure-latex/unnamed-chunk-40-1.pdf}}

Error bars here represent a 95\% CI after back transforming, and the red
dashed line represents the population level expectation on the
multiplicative scale after accounting for the fixed effects (x = 1
represents no effect on the multiplicative scale for body mass).

Multiplicative factors, at 95\% CI, range from \textasciitilde0.83 to
\textasciitilde1.20 across observers. The 95\% confidence intervals of
observers 1 and 2 do not cross the x = 1 line, indicating that observer
1 records masses \textasciitilde10\% higher (factor 1.10 {[}CI 1.01 -
1.20{]}), and observer 2 \textasciitilde9\% lower (factor 0.91 {[}CI
0.84 - 0.99{]}), than the population expectation in this model.

To assess whether observer random effects contribute significantly to
this model, a model without the observers will be fitted, as above with
parks:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# new model without observer random effect:}
\NormalTok{glmm\_no\_observer }\OtherTok{\textless{}{-}} \FunctionTok{update}\NormalTok{(glmm\_gauss2\_log, }\SpecialCharTok{\textasciitilde{}}\NormalTok{ . }\SpecialCharTok{{-}}\NormalTok{ (}\DecValTok{1} \SpecialCharTok{|}\NormalTok{ observer))}
\CommentTok{\# compare with anova:}
\FunctionTok{anova}\NormalTok{(glmm\_gauss2\_log, glmm\_no\_observer)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Data: df_clean
## Models:
## glmm_no_observer: log(body_mass) ~ landscape + vegetation + distance_to_water_km + , zi=~0, disp=~1
## glmm_no_observer:     (1 | park), zi=~0, disp=~1
## glmm_gauss2_log: log(body_mass) ~ landscape + vegetation + distance_to_water_km + , zi=~0, disp=~1
## glmm_gauss2_log:     (1 | park) + (1 | observer), zi=~0, disp=~1
##                  Df     AIC     BIC logLik deviance  Chisq Chi Df Pr(>Chisq)
## glmm_no_observer  6 -32.363 -10.795 22.182  -44.363                         
## glmm_gauss2_log   7 -52.258 -27.095 33.129  -66.258 21.895      1   2.88e-06
##                     
## glmm_no_observer    
## glmm_gauss2_log  ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
\end{verbatim}

As with parks, including observer as a random effect improves model fit
significantly (\(p = 2.88e-6\)), indicating meaningful body mass
variation across observers within the model.

\subsection{12. Conclusion}\label{conclusion}

Distance to water was a significant factor on giraffe body mass with a
1.2\% increase in body mass for every km further from water a giraffe is
observed in this model (\(p = 0.025\)), thus \(H_0\) may be rejected at
the 5\% significance level.

Increased body mass further from a water source may be a result of
reduced foraging competition away from busy water sites, or of unrelated
seasonal changes in body mass paired with different seasonal
distributions of water sites. Without temporal data included here it is
hard to disentangle. Furthermore, giraffe biology and behaviour also
need to be taken into account, given a typical roaming distance of 10km
and 1200kg mass, this would translate to a
\(1200 \times (1.012)^{10} - 1200 \approx 152\)kg difference, or a
12.7\% increase in body mass over this distance. Such a large increase
seems implausible biologically and likely reflects a lack of other
included predictors rather than a direct relationship between water
distance and body mass.

Additional meaningful variations in body mass factors were observed in
the park and observer random effects. Zebra Horizon Park masses were
recorded \textasciitilde10\% higher than the expected population value;
masses from observer 1 were \textasciitilde10\% higher, and observer 2
\textasciitilde9\% lower, than the expected population value. While
these random effects are not statistically significant in terms of \(p\)
value, they provide a large contribution to baseline body mass variation
in the population from different random effect levels. The variance in
the response explained by these random effects also far outweighed those
from the fixed effects (19.5\% vs.~2.7\%), which could indicates
potential biases, low quality data, or differences in the methods used
to measure body mass between observers as well as demonstrating the
limited power of the fixed effects in explaining body mass in this
model.

Given the high unexplained variance (77.9\%), the majority of the
model's prediction power comes from this variance, and the current
predictors have a relatively weak predictive power. This could be due to
missing other important predictors in the data such as: temporal data
(time since last drink, time of day, and season), temperatures,
population counts, elevation data, type of habitat, and vegetation
density and quality. If these predictor data were included, as well
changes from binary to more detailed descriptions for \texttt{landscape}
and \texttt{vegetation}, they could reduce residual variance, and
effectively move these predictor effects out of the unexplained variance
\(\epsilon_i\), and into the fixed effects. Increasing the predictive
abilities of the model would not necessarily uncover any other
significant predictors but it could shift their coefficients, standard
errors, and \(p\) values due to new interactions which could help reveal
significant predictors which are currently stored as ``noise'' within
the unexplained variance.

Overall, distance to water has a small but significant effect on giraffe
body mass in this model, but most of the observed variation remains
unexplained or associated with potential biases in random effects.

\end{document}
